from pathlib import Path

SOURCE_DIR      = "@PROJECT_SOURCE_DIR@"
BINARY_DIR      = "@CMAKE_BINARY_DIR@"
THIRD_PARTY_DIR = "@THIRD_PARTY_DIR@"
RELEASE         = "@CMAKE_BUILD_TYPE@".lower() == "release"

VAPI_COMPILE_DEFS   = """@VAPI_COMPILE_DEFS@"""
GLOBAL_COMPILE_DEFS = """@GLOBAL_COMPILE_DEFS@"""
