function(configure_apple_deployment_target)
    if("${CMAKE_OSX_ARCHITECTURES}" STREQUAL "")
        # Check if the target architecture is arm64
        include(CheckCXXSourceRuns)
        set(CMAKE_REQUIRED_FLAGS "-arch arm64")
        set(CHECK_ARM64_SOURCE_CODE "int main() { return 0; }")
        check_cxx_source_runs("${CHECK_ARM64_SOURCE_CODE}" IS_ARM64)
        if(IS_ARM64)
            set(CMAKE_OSX_ARCHITECTURES arm64 PARENT_SCOPE)
        else()
            set(CMAKE_OSX_ARCHITECTURES x86_64 PARENT_SCOPE)
        endif()
    endif()

    if (CMAKE_OSX_ARCHITECTURES MATCHES "arm64")
        message("Building on macOS M1 architecture (arm64)")
        set(CMAKE_OSX_DEPLOYMENT_TARGET "12.0" CACHE STRING "Minimum OS X deployment version" FORCE PARENT_SCOPE)
    else()
        message("Building on macOS x86 architecture")
        set(CMAKE_OSX_DEPLOYMENT_TARGET "10.15" CACHE STRING "Minimum OS X deployment version" FORCE PARENT_SCOPE)
        set(CMAKE_OSX_ARCHITECTURES "x86_64" CACHE STRING "macOS build architecture" FORCE PARENT_SCOPE)
    endif()
endfunction()
