package:
  name: vapor
  version: "3.6"

source:
  path: /vapor

#build:
#  script: |
#    pwd
#    echo unused

build:
  skip_compile_pyc:
    - "*.py"

requirements:
  build:
    # Build-Only
    # ==========================================
    - make=4.3
    - cmake=3.21.3
    - unzip=6.0
    - jupytext=1.13.8 # Generate notebooks
    - doxygen=1.9.1
    # Both
    # (Needs to be specified manually in both rather than just in host because otherwise conda will install multiple versions of some packages and break the install)
    # ==========================================
    # provides c++ compiler
    - cppyy=2.2.0
    - python=3.9.5
    - numpy=1.21.4
    - assimp=4.1.0
    - freetype=2.10.1
    - hdf5=1.12.1
    - jpeg=9e
    - geotiff=1.5.1
    - udunits2=2.2.26
    - netcdf4=1.5.8
    - libtiff=4.3.0
    - proj=6.2.0
    - glm=0.9.9.4
    - mesalib=21.2.5
  run:
    # Run only
    - xarray=2022.3.0
    - matplotlib=3.3.2 #=3.3.4
    - ipython=8.3.0 #=8.1.1
    - jupyter=1.0.0
    # Both
    - cppyy=2.2.0
    - python=3.9.5
    - numpy=1.21.4
    - assimp=4.1.0
    - freetype=2.10.1
    - hdf5=1.12.1
    - jpeg=9e
    - geotiff=1.5.1
    - udunits2=2.2.26
    - netcdf4=1.5.8
    - libtiff=4.3.0
    - proj=6.2.0
    - glm=0.9.9.4
    - mesalib=21.2.5


#- cmake=3.21.3
#- cppyy=2.2.0
#- python=3.9.5
#- assimp=4.1.0
#- freetype=2.10.1
#- hdf5=1.10.5
#- jpeg
#- geotiff=1.5.1
#- udunits2=2.2.26
#- netcdf4=4.7.0
#- libtiff=4.0.10
#- proj=6.1.1
#- glm
