package:
  name: vapor-maps
  version: "1.0.0"

source:
  - url: https://github.com/NCAR/VAPOR-Data/archive/refs/tags/1.0.tar.gz

build:
  noarch: generic
  script: |
    DEST="$PREFIX/share/images"
    install -d "$DEST"
    cp -r images/NaturalEarth* "$DEST"

