TOP = ../..

include ${TOP}/make/config/prebase.mk

LIBRARY = vdc
FILES = \
	BlkMemMgr Grid StructuredGrid RegularGrid \
	LayeredGrid \
# CurvilinearGrid NetCDFSimple \
	NetCDFSimple \
	NetCDFCollection NetCDFCFCollection \
	UDUnitsClass Proj4API DC VDC VDCNetCDF \
#	DCWRF DCCF DCMPAS DataMgr DataMgrUtils GeoUtil vizutil \
	KDTreeRG kdtree VDC_c

	

LIBRARIES += udunits2 proj

include ${TOP}/make/config/base.mk
