TOP = ../..

include ${TOP}/make/config/prebase.mk

MAKEFILE_CXXFLAGS = -DPACKAGE_NAME=\"patchelf\" \
	-DPACKAGE_TARNAME=\"patchelf\" -DPACKAGE_VERSION=\"0.8\" \
	-DPACKAGE_STRING=\"patchelf\ 0.8\" -DPACKAGE_BUGREPORT=\"\" \
	-DPACKAGE_URL=\"\" -DPACKAGE=\"patchelf\" -DVERSION=\"0.8\

PROGRAM = patchelf
FILES = patchelf

LIBRARIES = 

include ${TOP}/make/config/base.mk
