=begin comment

$Id$

=end comment

=head1 NAME

ptcl2vms - Transform lists of points into vms model files

=head1 SYNOPSIS

B<ptcl2vms> [options] I<point_files...> I<vmsfile> 

=head1 DESCRIPTION

B<ptcl2vms> reads newline-delimited 3D points from text files, where
coordinates are delimited with spaces, and stores a sequence of sphere
models in I<vmsfile>. The file I<vmsfile> will be created if it doesn't
already exist. Each sphere in the output represents a single point from
the inputs. Each input file is placed in its own timestep of the output
vms.

=head1 OPTIONS

=over 4

=item -radius E<lt>sizeE<gt>

Radius of spheres to produce (default 0.5)

=item -ref E<lt>numberE<gt>

Specify the number of refinement passes to do on sphere models (default 0)

=item -startts E<lt>tsE<gt>

Integer offset of first time step to produce in vms file. (default 0)

=item -stride E<lt>countE<gt>

Read one in every E<lt>countE<gt> points from the input files. (default 1)

=item -help 

Print a usage statement and then exit.

=item -quiet 

Operate quietly, only reporting fatal errors.

=back

=head1 EXAMPLES

ptcl2vms -help

ptcl2vms -radius 300 -ref 2 ts0points ts1points ts2points points.vms

ptcl2vms -startts 1 -radius 300 -ref 2 ts1points ts2points points.vms

ptcl2vms -stride 3 ts0points ts2points ts3points ts4points points.vms

ptcl2vms -quiet -startts 1 -radius 300 -ref 2 -stride 3 ts1points points.vms

=head1 SEE ALSO

I<Generation of model files which are sequences of points>

=head1 HISTORY

Last updated on $Date$
