=begin comment

$Id$

=end comment

=head1 NAME

vdcdump - Outputs information about a VDC Database

=head1 SYNOPSIS

B<vdcdump> [options] I<source.nc> 

B<vdcdump> [-h] [-v] [-nc-order] -I<source.nc>

=head1 DESCRIPTION

B<vdcdump> prints information about data stored in a VDC database, I<source.nc>. By default, 
it prints coordinates, dimensions, and user-defined attributes. Additional information pertaining 
to the VDC data format can be outputted with the -v verbose option.

=head1 OPTIONS

=over 4

=item -v

Verbose output. Prints additional information specific to the VDC data format.

=item -nc-order

Reverses order of dimensions to match that of the NetCDF format (slowest to fastest varying). 
By default, dimensions are ordered from fastest to slowest varying.


=head1 EXAMPLES


C<vdcdump path/to/source.nc>


=head1 SEE ALSO


I<Output information >

=head1 HISTORY

Last updated on $Date$

