name: Trigger Documentation Update

on:
  release:
    types: [published]
  push:
    branches:
        - Actions

jobs:
  trigger-doc-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout VAPOR repo
        uses: actions/checkout@v4

      - name: Trigger documentation update
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/NCAR/VaporDocumentationWebsite/dispatches \
          -d '{"event_type":"update-docs"}'