#pragma once

class PTransformWidget;
class PAnnotationColorbarWidget;
class PButton;
class PCheckbox;
class PColorSelector;
class PCopyRegionWidget;
class PDisplay;
class PDoubleInput;
class PEnumDropdown;
class PFidelitySection;
class PFileSelector;
class PGeometrySubtab;
class PGroup;
class PIntegerInput;
class PLabel;
class PMultiVarSelector;
class POrientationSelector;
class PRegionSelector;
class PSection;
class PSliderEdit;
class PStringDropdown;
class PStringInput;
class PTFEditor;
class PVariableWidgets;
class PShowIf;
