#!/bin/sh
#

BRANCH=`git rev-parse --abbrev-ref HEAD`

# If our current branch does not exist in the remote repository yet, then compare
# our local changes with main.  Otherwise, compare our local changes with the remote
# branch.
if [ `git ls-remote --heads https://github.com/NCAR/VAPOR.git $BRANCH | wc -l` = 0 ]; then
    COMPARE_BRANCH="main"
else
    COMPARE_BRANCH=$BRANCH
fi

# If we're on the readTheDocs branch, skip clang-format
#
if [ "$BRANCH" = "readTheDocs" ]; then
    echo "pre-push hook skipped for current branch."

# Otherwise format the changed lines in all commits up to this push
#
else
    for COMMIT in $(git log --pretty=format:%h origin/$COMPARE_BRANCH...$BRANCH); do
        echo "Reading Commit: $COMMIT"
        for FILE in $(git diff-tree --no-commit-id --name-only -r $COMMIT |grep -E "\.h|\.cpp"); do
            NUMBERS=""
            for NUMBER in $(git blame --line-porcelain "$FILE" | egrep ^$COMMIT | cut -d' ' -f3); do
                NUMBERS="$NUMBERS --lines $NUMBER:$NUMBER "
            done

            if [ "$NUMBERS" != "" ]; then
                echo "  Running clang-format on $FILE"
                clang-format -i $FILE $NUMBERS
                git add $FILE
            fi
        done
    done

    git commit -m "clang-format pre-push hook"

    # git commit will return non-zero status if there's nothing to commit.  Make sure
    # we return 0 so git 'push' will still be invoked
    exit 0
fi
